config/routes.rb
Rails.application.routes.draw do
  resources :logins

  get "generate_password", to: "logins#generate_password"
  get "generate_username", to: "logins#generate_username"

  root "logins#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
    validates :name, :username, :password, :url, presence: true

    def self.generate_username (words = 3)
      Faker::Name.first_name.downcase + "." + Faker::Verb.simple_present.downcase + "." + Faker::Creature::Animal.name.downcase
    end

    def self.generate_password(len = 12)
      Faker::Internet.password(min_length: len)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  require 'email_server'

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
    @login.username = Login.generate_username
    @login.password = Login.generate_password

    @email_accounts = get_email_accounts
  end

  # GET /logins/1/edit
  def edit
    @email_accounts = get_email_accounts
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    try_saving = @login.valid?

    if (try_saving && @login.alias_of != "")
      resp = EmailServer::Miab.alias_add(@login.username, @login.alias_of)
      if resp.code == 200
        try_saving = true
      else
        try_saving = false
        @login.errors.add(:alias_of, "Couldn't create the alias on email server.")
      end
    end

    respond_to do |format|
      if (try_saving && @login.save)
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        @login.assign_attributes(login_params)
        @email_accounts = get_email_accounts
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    test_login = Login.new(login_params)
    try_updating = test_login.valid?
    if !try_updating
      @login.errors.merge!(test_login.errors)
      @login.assign_attributes(login_params)
    end

    # had alias | no alias => destroy old
    # had alias | different alias => destroy old AND create new
    # no alias | has alias => create new
    username_change = @login.username != login_params[:username]

    # alias of change => destroy old AND create new
    alias_of_change = (@login.alias_of != "") && (login_params[:alias_of] != "") && (@login.alias_of != login_params[:alias_of])

    if try_updating
      err = []
      if (username_change && @login.alias_of != "") || alias_of_change
        resp = EmailServer::Miab.alias_remove(@login.username)
        if resp.code != 200
          err << "Failed to remove old alias on email server"
        end
      end
      if (username_change && login_params[:alias_of] != "") || alias_of_change
        resp = EmailServer::Miab.alias_add(login_params[:username], login_params[:alias_of])
        if resp.code != 200
          err << "Failed to create new alias on email server"
        end
      end
      if err.length > 0
        try_updating = false
        @login.errors.add(:alias_of, err.join(", "))
      end
    end

    respond_to do |format|
      if try_updating && @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        @login.assign_attributes(login_params)
        @email_accounts = get_email_accounts
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    alias_deleted = true
    if @login.alias_of != ""
      resp = EmailServer::Miab.alias_remove(@login.username)
      alias_deleted = (resp.code == 200)
    end

    respond_to do |format|
      if alias_deleted
        @login.destroy
        format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to logins_url, alert: 'Failed to delete alias on th email server.' }
        format.json { head :no_content }
      end
    end
  end

  def generate_username
    respond_to do |format|
      format.json do
        @username = Login.generate_username
      end
    end
  end

  def generate_password
    respond_to do |format|
      format.json do
        @pwd = Login.generate_password
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def login_params
      params.require(:login).permit(:name, :username, :password, :url, :alias_of)
    end

    def get_email_accounts
      resp = EmailServer::Miab.emails_get
      resp.body.to_s.split("\n").map { |e| [e] }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/layouts/_alerts.html.slim
- if notice
  .alert.alert-success.alert-dismissible.fade.show[role="alert"]
    = notice
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"] &times;

- if alert
  .alert.alert-danger.alert-dismissible.fade.show[role="alert"]
    = alert
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"] &times;

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  a.navbar-brand href="#{logins_path}"
    = image_tag("logo.png")
    | &nbsp;TokenMail

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Tokenmail
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/navbar"
    .container-fluid
      .row.justify-content-center
        .col-6
          = render "layouts/alerts"
          = yield

app/views/logins/_form.html.slim
= bootstrap_form_for(@login) do |f|
  = f.text_field :name
  .form-row
    .col
      = f.text_field :username, append: link_to(fa_icon("undo"), generate_username_path, id: "generateUsername", remote: true, class: "btn btn-success")
    .col
      = f.text_field :password, append: link_to(fa_icon("undo"), generate_password_path, id: "generatePassword", remote: true, class: "btn btn-success")
  = f.select :alias_of, @email_accounts, include_blank: true, help: "The email address this login is associated with"
  = f.text_field :url

  = f.submit "Save", class: "btn btn-primary mr-2"
  = link_to "Cancel", logins_path, class: "btn btn-link"

app/views/logins/edit.html.slim
h1 Editing Login

= render 'form', login: @login

app/views/logins/index.html.slim
h1
  | Logins
  = link_to fa_icon("plus"), new_login_path, class: "btn btn-primary float-right mt-2"

table.table
  thead
    tr
      th Name
      th Username
      th Url
      th Actions
  tbody
    - @logins.each do |login|
      tr
        td= login.name
        td= login.username
        td= login.url
        td
          = link_to fa_icon("eye"), login, class: "btn btn-sm btn-primary mr-2"
          = link_to fa_icon("pen"), edit_login_path(login), class: "btn btn-sm btn-success mr-2"
          = link_to fa_icon("trash-alt"), login, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger"

app/views/logins/new.html.slim
h1 New Login

= render 'form', login: @login

app/views/logins/show.html.slim
h1
  | Login Details -&nbsp;
  small.text-muted= @login.name
  = link_to fa_icon("trash-alt"), @login, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger float-right mt-2"
  = link_to fa_icon("pen"), edit_login_path(@login), class: "btn btn-success float-right mt-2 mr-2"


dl.row
  dt.col-3 Username
  dd.col-9= @login.username

  dt.col-3 Password
  dd.col-9= @login.password

  dt.col-3 Alias of
  dd.col-9= @login.alias_of == "" ? "--" : @login.alias_of
    
  dt.col-3 Url
  dd.col-9= @login.url